###################################################################
#           Makefile for  DNS CODE
###################################################################
#
########################################################## compiler
#F77 = f90
#F77= mpif77
F77 = mpif77
CMPI_LIB =
OMP_FLAGS =
#F77 = mpxlf
#
#################################################### compiler flags
#### F77FLAGS = -c -O3 -tpp7 -xW -w -pg
#F77FLAGS = -c -O3 -xW -w
    

#### LFLAGS  = -O3 -tpp7 -xW -w -pg -CB
#LFLAGS  = -O3 -xW -w 

F77FLAGS = -c -O3 -w
LFLAGS  = -O3 -w

#CCFLAGS = -O3 -c -qmaxmem=-1 -qcache=auto -qaltivec \
#          -q64 -qarch=ppc970 -qtune=ppc970 -pg
#             
#
#
#
########################################################### machine
#SYSTEM = ibm6000
##################################################### objects alpha
INIT = .
SRCDIR = $(INIT)
OBJ=$(INIT)
OBJDIR = $(OBJ)
CALCDIR =$(INIT)

OBJECTS = $(OBJ)/main.o\
$(OBJ)/cftsingle.o\
$(OBJ)/rftsingle.o\
$(OBJ)/fou3D.o\
$(OBJ)/cross.o\
$(OBJ)/laps.v7.o\
$(OBJ)/change.allfac.o\
$(OBJ)/cfdiff8.v7.o\
$(OBJ)/modules.v7.o
#
#################################################### compile 
#
$(OBJDIR)/modules.v7.o : $(SRCDIR)/modules.v7.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile
	@echo compiling modules.v7.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/modules.v7.f
#
$(OBJDIR)/main.o : $(SRCDIR)/main.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile $(SRCDIR)/modules.v7.o
	@echo compiling main.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/main.f
#
$(OBJDIR)/cftsingle.o : $(SRCDIR)/cftsingle.f $(SRCDIR)/makefile
	@echo compiling cftsingle.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/cftsingle.f
#
$(OBJDIR)/rftsingle.o : $(SRCDIR)/rftsingle.f $(SRCDIR)/makefile
	@echo compiling rftsingle.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/rftsingle.f
#
$(OBJDIR)/fou3D.o : $(SRCDIR)/fou3D.f $(SRCDIR)/ctes3D $(SRCDIR)/makefile
	@echo compiling fou3D.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/fou3D.f
#
$(OBJDIR)/cross.o : $(SRCDIR)/cross.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile
	@echo compiling cross.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/cross.f
#
$(OBJDIR)/laps.v7.o : $(SRCDIR)/laps.v7.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile $(SRCDIR)/modules.v7.o
	@echo compiling laps.v7.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/laps.v7.f
#
$(OBJDIR)/change.allfac.o : $(SRCDIR)/change.allfac.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile
	@echo compiling change.allfac.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/change.allfac.f
#
$(OBJDIR)/cfdiff8.v7.o : $(SRCDIR)/cfdiff8.v7.f  $(SRCDIR)/ctes3D $(SRCDIR)/makefile $(SRCDIR)/modules.v7.o
	@echo compiling cfdiff8.v7.f
	@cd $(OBJDIR); $(F77) $(F77FLAGS) -I$(SRCDIR) $(SRCDIR)/cfdiff8.v7.f
#
############################################################ build
ROUGHv7    :printmsgA $(OBJECTS)
	@echo Linking... 
	@$(F77) -o $@ $(OBJECTS) $(LFLAGS)
	@echo ROUGHv7 built, congratulations.
#
########################################################## message
printmsgA :
	@echo
	@echo Building ROUGHv7 for $(SYSTEM)
	@echo Compiler flags : $(F77FLAGS)
	@echo Linker   flags : $(LFLAGS)
#
###################################################### end of file
